version: 2
jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Checkout Infrastructure
          command: |
            git clone git@github.com:eslater/wp-site-infrastructure.git tools 
      - setup_remote_docker
      - run:
          name: Install Dependencies 
          command: apt-get update; apt-get install -y openssh-client ca-certificates openssl;
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Login to Docker Hub 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Build Image 
          command: |
            cp tools/docker/* .
            docker build -t $PUBLISHED_IMAGE_NAME:$CIRCLE_BUILD_NUM -t $PUBLISHED_IMAGE_NAME:latest .
      - run: 
          name: Push to Docker Hub 
          command: |
            docker push $PUBLISHED_IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $PUBLISHED_IMAGE_NAME:latest
  staging:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies 
          command: apt-get update; apt-get install -y openssh-client ca-certificates openssl;
      - run:
          name: Move Site Bundle to Droplet
          command: scp -o StrictHostKeyChecking=no initdata.sql $STAGING_USER@$STAGING_IP:~
      - run:
          name: Deploy Latest
          command: ssh -o StrictHostKeyChecking=no $STAGING_USER@$STAGING_IP "./pull-latest-and-redeploy.sh"
  production:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies 
          command: apt-get update; apt-get install -y openssh-client ca-certificates openssl;
      - run:
          name: Move Site Bundle to Droplet
          command: scp -o StrictHostKeyChecking=no initdata.sql $PRODUCTION_USER@$PRODUCTION_IP:~
      - run:
          name: Deploy Latest
          command: ssh -o StrictHostKeyChecking=no $PRODUCTION_USER@$PRODUCTION_IP "./pull-latest-and-redeploy.sh"
workflows:
  version: 2
  wp-build-deploy-pipeline:
    jobs:
      - build
      - staging:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - staging 
      - production:
          requires:
            - hold
